#spring.cloud.config.uri=http://localhost:8888
#spring.config.import=optional:configserver:

#########################################################

spring.application.name=monolith
server.port=8070

spring.profiles.active=prod
spring.jpa.open-in-view=false

logging.level.root=ERROR
logging.level.com.example=INFO