server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # ????? Eureka Server
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
