spring.cloud.config.uri=http://localhost:8888
spring.config.import=optional:configserver:

#########################################################

spring.application.name=department-service
server.port=8081

spring.profiles.active=prod
spring.jpa.open-in-view=false

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.root=ERROR
logging.level.com.example=INFO