server:
  port: 8082

spring:
  application:
    name: admin-service

  boot:
    admin:
      context-path: /admin
      ui:
        title: 'Spring Boot Admin'
      instance:
        prefer-ip-address: true
      management:
        endpoints:
          web:
            exposure:
              include: '*'
  security:
    user:
      name: admin
      password: secret

  cloud:
    discovery:
      client:
        service:
          url: http://localhost:8761/eureka/

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
