spring.application.name=eureka-service
server.port=8761

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Настройка клиента Spring Boot Admin
spring.boot.admin.client.url=http://localhost:8082
management.endpoints.web.exposure.include=*

# Включаем подробную информацию о состоянии
management.endpoint.health.show-details=always