spring.application.name=eureka-service
server.port=8761

# Eureka server configuration
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Management endpoints configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
